ArturoEstNav/rails-remotedesk

- app/models/match.rb
- app/models/offer.rb
- app/models/offer_tag.rb
- app/models/tag.rb
- app/models/user.rb
- db/migrate/20200808153144_add_columns_to_users.rb
- db/migrate/20200808164325_create_offers.rb
- db/migrate/20200808165506_remove_schedule_from_offers.rb
- db/migrate/20200808170016_create_matches.rb
- db/migrate/20200808170452_create_tags.rb
- db/migrate/20200808170632_create_offer_tags.rb
- db/schema.rb
- test/models/match_test.rb
- test/models/offer_tag_test.rb
- test/models/offer_test.rb
- test/models/tag_test.rb
All models have been completed
-users with validations
-tags with validations
-offers with validations
-matches with validations
-offer_tags
> Models creation

- app/models/user.rb
Fixes user validations and added matches association
> fixed user validations and connected matches in users

- app/controllers/application_controller.rb
- app/controllers/matches_controller.rb
- app/controllers/offers_controller.rb
- app/controllers/tag_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/matches/index.html.erb
- app/views/matches/new.html.erb
- app/views/offers/index.html.erb
- app/views/offers/show.html.erb
- app/views/users/edit.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- test/controllers/matches_controller_test.rb
- test/controllers/offers_controller_test.rb
- test/controllers/tag_controller_test.rb
- test/controllers/users_controller_test.rb
All controlers were laid out, some actions still need work
> Controller creation

- app/controllers/matches_controller.rb
- app/views/offers/index.html.erb
The view for the offers index has been laid out, not completed yet though
> Index view

- app/controllers/pages_controller.rb
- app/jobs/offer_job.rb
- app/views/pages/home.html.erb
- config/routes.rb
- db/migrate/20200815203100_add_admin_to_users.rb
- db/schema.rb
- test/jobs/offer_job_test.rb
> changes for search and first work on syncjob

- lib/scraper_indeed.rb
Why? Heroku broke and I think that it is due to me forgetting to king a pry-byebug
How? removed it
> removed pry-byebug

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_custom_card.scss
- app/assets/stylesheets/components/_custom_container.scss
- app/assets/stylesheets/components/_custom_text.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/shared/_navbar.html.erb
> manita de gato 1

- app/controllers/pages_controller.rb
- app/views/offers/index.html.erb
- app/views/pages/home.html.erb
Fixed a route path in button to save offer.
> fixed route to sign up in button save

- db/seeds.rb
removed indeed for now since we got banned by the site
> removing indeed for now

- app/assets/stylesheets/config/_colors.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/pages/home.html.erb
> its pretty now

- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
- db/migrate/20200822182054_add_location_type_to_offers.rb
- db/schema.rb
Query filters in searchbar for better matches
> Query filters in searchbar

- app/controllers/pages_controller.rb
WHy? I accidentally killed a variable and the homepage wont display offers
How? added it again
> added variable to populate with offers the homepage

- lib/api_offer.rb
> Searchbar buttons

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_custom_card.scss
- app/assets/stylesheets/components/_custom_container.scss
- app/assets/stylesheets/components/_custom_text.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
> front end so far

- db/seeds.rb
> Seeds to test job_types in searchbar

- app/controllers/application_controller.rb
- app/helpers/meta_tags_helper.rb
- app/views/layouts/application.html.erb
- app/views/offers/show.html.erb
- app/views/pages/home.html.erb
- config/initializers/default_meta.rb
- config/meta.yml
> Metatags configuration

- app/helpers/meta_tags_helper.rb
- config/meta.yml
- public/404.html
> Le wagon list

- app/assets/stylesheets/components/_custom_button.scss
- app/assets/stylesheets/components/_custom_card.scss
- app/assets/stylesheets/components/_custom_container.scss
- app/assets/stylesheets/components/_custom_text.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/offers/index.html.erb
- app/views/offers/show.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
Spaces mostly unified, just need to tweak an infinite amount of little details
> Feature unifying spaces

- app/assets/stylesheets/components/_custom_button.scss
- app/assets/stylesheets/components/_custom_container.scss
- app/assets/stylesheets/components/_custom_text.scss
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/shared/_navbar.html.erb
- app/views/users/edit.html.erb
Why?
Devise didnt have any styling, i looked out of rails
How?
applied buttons and spacing to it
> Feature embelishing devise forms

- app/controllers/application_controller.rb
Something got broken and devise wouldnt ask for the customer name from the get go, it has been resolved now
###How?
Adding some devise sanitizers to the devise page
> Users are now able to fill their info from the get go

- db/seeds.rb
i removed indeed in the meantime since they changed the way they store their info
> removed indeed while i troubleshoot it

- public/404.html
- public/500.html
> Solved typos on 404-500 pages

- app/helpers/meta_tags_helper.rb
> image fixed

- app/assets/stylesheets/components/_custom_button.scss
- app/assets/stylesheets/components/_custom_container.scss
- app/assets/stylesheets/components/_custom_helper_elements.scss
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/offers/new.html.erb
- app/views/users/edit.html.erb
> Feature embellishments

- app/assets/stylesheets/components/_custom_button.scss
- app/assets/stylesheets/components/_custom_card.scss
- app/assets/stylesheets/components/_custom_container.scss
- app/assets/stylesheets/components/_custom_text.scss
- app/assets/stylesheets/components/custom_table.scss
- app/views/offers/show.html.erb
- app/views/pages/home.html.erb
- app/views/users/show.html.erb
**Why?
The site was not responsive enough, it is now
**How?
Html was re written and most css got delegated from bootstrap to css to be more manageable
> Fix carousel display

- db/seeds.rb
- lib/scraper_indeed.rb
**Why?**
The scraper was broken due to Indeed changing the structure of their site
**How?**
Got it fixed
> Fix indeed scraping

- db/seeds.rb
- lib/scraper_indeed.rb
Had a mess up on the URL to redirect to posting site, got it corrected
> Fix indeed link
